### ISSUE TITLE
[NEW FEATURE] Warning team switch + mail

### ISSUE THREAD

**Issue by mathisfchx** [TC-netw4ppl/TC-netw4ppl-app#136]
**Description of the desired solution**
Popup after the GET if the web give you a new_team tag.
This popup ask you if you accept to change team : 
-> If you do accept : Force Push 
-> If you reject : You can accept later in the settings tab

**Comment by lduf** [comment]
Display new configuration file downloaded only if fields are changed

**Comment by mathisfchx** [comment]
--> chosen solution : just a warning message to have the possiblity to send by mail the data before erasing it
